### ISSUE TITLE
Logger Accept Lambda for LogBuilder

### ISSUE THREAD

**Issue by vjkoskela** [ArpNetworking/logback-steno#30]
The custom LogbackSteno logger's LogBuilder methods should be extended to support accepting a lambda which accepts an instance of LogBuilder and returns void. Something like this:

```java
LOGGER.info(lb -> lb.setMessage("Hello World!").addData("myWorld", world));
```

Some of the caveats here. For starters we will need a separate LogBuilder interface without the log method to avoid either 1) double logging by both users and logger calling log in the lambda, 2) no logging by having the user forget to call log in the lambda.

**Comment by BrandonArp** [comment]
Closed by #32
