### ISSUE TITLE
Why is version always '0'?

### ISSUE THREAD

**Issue by david30xie** [ArpNetworking/logback-steno#56]
In this file [StenoEncoder.java](https://github.com/ArpNetworking/logback-steno/blob/master/src/main/java/com/arpnetworking/logback/StenoEncoder.java#L649), `version` is set to `0`, what is this version used for? Is it version of logs?

**Comment by BrandonArp** [comment]
This is the version of the Steno spec that we adhere to. This field allows us to evolve the spec while allowing downstream parsers to parse a variety of versions with no ambiguity. Think of it like API versioning.

**Comment by david30xie** [comment]
I see. I thought it is version for our logs.

Thank you for clarification.

**Comment by BrandonArp** [comment]
If you want to log the version if your application, the context block would be a good place.

**Comment by david30xie** [comment]
yes, that makes sense.
Thanks!
